In [1]:
import pandas as pd
import re

In [2]:
bttv = "5Head AINTNOWAY Aware AYAYA BOOBA catJAM Clap Clueless COPIUM ddHuh DIESOFCRINGE elmoFire EZ FeelsWeirdMan gachiGASM gachiHYPER GIGACHAD HACKERMANS Hmmm HUHH KEKW KKomrade LULW MadgeLate modCheck monkaTOS monkaW MONKE NERD NODDERS NOOO OMEGALUL OOOO PauseChamp peepoGiggles pepeD PepeHands pepeJAM PepeLaugh Pog POGGERS PogO Sadge SNIFFA tenseSmash WAYTOODANK weirdChamp WOTT"
word_list = bttv.split(' ')

In [3]:
# Read the list of filenames from the configuration file
with open('file_list.txt', 'r', encoding='utf-8') as config_file:
    file_names = config_file.read().splitlines()

# Regex pattern to match the data format
pattern = r'\[(.*?)\] (.*?): (.*)'


# Initialize an empty list to store parsed data
datalist = []
stream_count = 0
# Iterate over each specified file
for file in file_names:
    full_path = file
    with open(full_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        for line in lines:
            match = re.match(pattern, line)
            if match:
                date, user, message = match.groups()
                datalist.append([date, user, message,stream_count])
    stream_count = stream_count + 1

# Create a DataFrame from the parsed data
data = pd.DataFrame(datalist, columns=["date", "user", "message","stream"])

In [4]:
data.shape

(145708, 4)

In [6]:

word_count = {word: 0 for word in word_list}

word_pattern = r"[\w!+:]+\b"

word_count = {word: 0 for word in word_list}

for message in data['message']:
    words = re.findall(word_pattern, message)
    for word in word_list:
        word_count[word] += words.count(word)

In [7]:
df = pd.DataFrame(list(word_count.items()), columns=['Word', 'Count'])

# Optionally, set 'Word' column as index
df.set_index('Word', inplace=True)

# Display the DataFrame
print(df)

               Count
Word
5Head             94
AINTNOWAY        461
Aware            284
AYAYA             32
BOOBA             60
catJAM            96
Clap             452
Clueless         369
COPIUM           130
ddHuh              5
DIESOFCRINGE     163
elmoFire          28
EZ              1717
FeelsWeirdMan     25
gachiGASM          8
gachiHYPER        35
GIGACHAD         490
HACKERMANS        21
Hmmm             100
HUHH              53
KEKW             153
KKomrade           7
LULW             430
MadgeLate          5
modCheck          51
monkaTOS           3
monkaW           150
MONKE             16
NERD              23
NODDERS          181
NOOO             146
OMEGALUL         936
OOOO             120
PauseChamp       336
peepoGiggles      55
pepeD             16
PepeHands         43
pepeJAM           15
PepeLaugh        860
Pog              480
POGGERS           40
PogO              11
Sadge            228
SNIFFA            32
tenseSmash         8
WAYTOODANK        50
weirdChamp        73
WOTT               4

In [8]:
df.describe()

             Count
count    48.000000
mean    189.479167
std     309.782902
min       3.000000
25%      22.500000
50%      57.500000
75%     192.750000
max    1717.000000

In [9]:
max_row = df[df['Count'] == df['Count'].max()]

# Write out the max row
print("\nRow with maximum count:")
print(max_row)

Row with maximum count:
      Count
Word
EZ     1717

In [10]:
df = df.sort_values(by='Count')

In [11]:
df.tail()

           Count
Word
Pog          480
GIGACHAD     490
PepeLaugh    860
OMEGALUL     936
EZ          1717

In [14]:
notused = df[df['Count']<80]

In [15]:
notused

               Count
Word
monkaTOS           3
WOTT               4
ddHuh              5
MadgeLate          5
KKomrade           7
gachiGASM          8
tenseSmash         8
PogO              11
pepeJAM           15
MONKE             16
pepeD             16
HACKERMANS        21
NERD              23
FeelsWeirdMan     25
elmoFire          28
AYAYA             32
SNIFFA            32
gachiHYPER        35
POGGERS           40
PepeHands         43
WAYTOODANK        50
modCheck          51
HUHH              53
peepoGiggles      55
BOOBA             60
weirdChamp        73