In [1]:
import pandas as pd
import re
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import numpy as np

# Read the list of filenames from the configuration file
with open('file_list.txt', 'r', encoding='utf-8') as config_file:
    file_names = config_file.read().splitlines()

# Regex pattern to match the data format
pattern = r'\[(.*?)\] (.*?): (.*)'

# Initialize an empty list to store parsed data
datalist = []
stream_count = 0
# Iterate over each specified file
for file in file_names:
    full_path = "data\\"+file
    with open(full_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        for line in lines:
            match = re.match(pattern, line)
            if match:
                date, user, message = match.groups()
                datalist.append([date, user, message,stream_count])
    stream_count = stream_count + 1

# Create a DataFrame from the parsed data
data = pd.DataFrame(datalist, columns=["date", "user", "message","stream"])

data['date'] = pd.to_datetime(data['date'])

In [2]:
paul = data[data['user']=='1206paul_']

In [3]:
filtered_data = paul[paul['message'].str.contains('ugly', case=False, na=False)]

In [4]:
filtered_data

,date,user,message,stream
64496,2024-05-27 18:28:03+00:00,1206paul_,hot bitches are never ugly (like me),24
76425,2024-05-29 19:05:54+00:00,1206paul_,70k is such an ugly number,26
261672,2024-08-19 12:01:19+00:00,1206paul_,Fucking ugly bitch*,88
318644,2024-09-05 14:19:52+00:00,1206paul_,"nice guys be like: ""i didnt like you to begin ...",104
367939,2024-09-17 17:06:10+00:00,1206paul_,your feet are fugly,114
398772,2024-09-26 13:06:16+00:00,1206paul_,you are ugly btw,122
399369,2024-09-26 14:11:21+00:00,1206paul_,i never called you ugly,122
455807,2024-10-14 15:33:31+00:00,1206paul_,By hotel ugly,136
455809,2024-10-14 15:33:39+00:00,1206paul_,Shut up My Moms Calling Hotel Ugly,136