In [1]:
import pandas as pd
import re
import matplotlib.pyplot as plt

# Read the list of filenames from the configuration file
with open('file_list.txt', 'r', encoding='utf-8') as config_file:
    file_names = config_file.read().splitlines()

# Regex pattern to match the data format
pattern = r'\[(.*?)\] (.*?): (.*)'


# Initialize an empty list to store parsed data
datalist = []
stream_count = 0
# Iterate over each specified file
for file in file_names:
    full_path = file
    with open(full_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        for line in lines:
            match = re.match(pattern, line)
            if match:
                date, user, message = match.groups()
                datalist.append([date, user, message,stream_count])
    stream_count = stream_count + 1

# Create a DataFrame from the parsed data
data = pd.DataFrame(datalist, columns=["date", "user", "message","stream"])

In [2]:
data = data[data.apply(lambda row: row['user'].lower() in row['message'].lower(), axis=1)]

In [3]:
data.count()

date       2005
user       2005
message    2005
stream     2005
dtype: int64

In [4]:
data.head(25)

,date,user,message,stream
100,2024-05-01 15:13:16 UTC,kloakpojken,4 raiders from kloakpojken have joined!,0
120,2024-05-01 15:14:42 UTC,yusuf2774,yusuf2774 is gifting 1 Tier 1 Subs to dorozea'...,0
121,2024-05-01 15:14:43 UTC,yusuf2774,yusuf2774 gifted a Tier 1 sub to ChickenBurgah...,0
210,2024-05-01 15:26:58 UTC,iborotti_06,iborotti_06 subscribed with Prime.,0
566,2024-05-01 16:29:11 UTC,x3lolx,x3lolx is gifting 1 Tier 1 Subs to dorozea's c...,0
567,2024-05-01 16:29:11 UTC,x3lolx,x3lolx gifted a Tier 1 sub to ArtMassong!,0
568,2024-05-01 16:30:00 UTC,x3lolx,x3lolx is gifting 1 Tier 1 Subs to dorozea's c...,0
569,2024-05-01 16:30:00 UTC,x3lolx,x3lolx gifted a Tier 1 sub to PrachtkerleDE!,0
575,2024-05-01 16:31:10 UTC,x3lolx,x3lolx is gifting 1 Tier 1 Subs to dorozea's c...,0
576,2024-05-01 16:31:10 UTC,x3lolx,x3lolx gifted a Tier 1 sub to lubb1x!,0
660,2024-05-01 16:41:16 UTC,x3lolx,x3lolx is gifting 1 Tier 1 Subs to dorozea's c...,0
661,2024-05-01 16:41:16 UTC,x3lolx,x3lolx gifted a Tier 1 sub to alaskalyeska!,0
866,2024-05-01 17:19:54 UTC,ze1nar,ze1nar subscribed with Prime. They've subscrib...,0
1061,2024-05-01 17:52:19 UTC,spinglebob,spinglebob subscribed at Tier 1. They've subsc...,0
1075,2024-05-01 17:54:28 UTC,Bizzan,Bizzan is gifting 5 Tier 1 Subs to dorozea's c...,0
1076,2024-05-01 17:54:29 UTC,Bizzan,Bizzan gifted a Tier 1 sub to shotashellz!,0
1077,2024-05-01 17:54:29 UTC,Bizzan,Bizzan gifted a Tier 1 sub to aabeemick!,0
1078,2024-05-01 17:54:29 UTC,Bizzan,Bizzan gifted a Tier 1 sub to gantl4!,0
1079,2024-05-01 17:54:29 UTC,Bizzan,Bizzan gifted a Tier 1 sub to Minaqua__!,0
1080,2024-05-01 17:54:29 UTC,Bizzan,Bizzan gifted a Tier 1 sub to FeiFuchs!,0
1496,2024-05-01 19:05:22 UTC,lucas_bke,lucas_bke subscribed at Tier 1. They've subscr...,0
1633,2024-05-01 19:25:40 UTC,bbarrannn,bbarrannn subscribed at Tier 1. They've subscr...,0
1655,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn is gifting 10 Tier 1 Subs to dorozea...,0
1656,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to Manuel_98!,0
1657,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to xGoron!,0

In [5]:
giftedData = data[data['message'].str.contains(' sub ', case=False, na=False)]

In [6]:
giftedData.head(50)

,date,user,message,stream
121,2024-05-01 15:14:43 UTC,yusuf2774,yusuf2774 gifted a Tier 1 sub to ChickenBurgah...,0
567,2024-05-01 16:29:11 UTC,x3lolx,x3lolx gifted a Tier 1 sub to ArtMassong!,0
569,2024-05-01 16:30:00 UTC,x3lolx,x3lolx gifted a Tier 1 sub to PrachtkerleDE!,0
576,2024-05-01 16:31:10 UTC,x3lolx,x3lolx gifted a Tier 1 sub to lubb1x!,0
661,2024-05-01 16:41:16 UTC,x3lolx,x3lolx gifted a Tier 1 sub to alaskalyeska!,0
1076,2024-05-01 17:54:29 UTC,Bizzan,Bizzan gifted a Tier 1 sub to shotashellz!,0
1077,2024-05-01 17:54:29 UTC,Bizzan,Bizzan gifted a Tier 1 sub to aabeemick!,0
1078,2024-05-01 17:54:29 UTC,Bizzan,Bizzan gifted a Tier 1 sub to gantl4!,0
1079,2024-05-01 17:54:29 UTC,Bizzan,Bizzan gifted a Tier 1 sub to Minaqua__!,0
1080,2024-05-01 17:54:29 UTC,Bizzan,Bizzan gifted a Tier 1 sub to FeiFuchs!,0
1656,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to Manuel_98!,0
1657,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to xGoron!,0
1658,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to tinyballls!,0
1659,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to biggestwiseguy!,0
1660,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to doenietjiggy!,0
1661,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to casperblank!,0
1662,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to kalakg__freboy!,0
1663,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to fnc_is_calling!,0
1664,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to blind_dood!,0
1665,2024-05-01 19:27:44 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to Hitmonchop!,0
1707,2024-05-01 19:33:58 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to z1jan2k!,0
1708,2024-05-01 19:33:58 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to j0nas_164!,0
1709,2024-05-01 19:33:58 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to FilipB01!,0
1710,2024-05-01 19:33:58 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to Baffleturd!,0
1711,2024-05-01 19:33:58 UTC,bbarrannn,bbarrannn gifted a Tier 1 sub to RedEzzyz!,0
2215,2024-05-02 15:13:04 UTC,gyllenc,gyllenc gifted a Tier 1 sub to b__ki!,1
2336,2024-05-02 15:25:04 UTC,ardaabora,ardaabora gifted a Tier 1 sub to yuki2803!,1
2337,2024-05-02 15:25:04 UTC,ardaabora,ardaabora gifted a Tier 1 sub to gabrielius2019!,1
2338,2024-05-02 15:25:04 UTC,ardaabora,ardaabora gifted a Tier 1 sub to FadesOO!,1
2339,2024-05-02 15:25:04 UTC,ardaabora,ardaabora gifted a Tier 1 sub to kstaann!,1
2340,2024-05-02 15:25:04 UTC,ardaabora,ardaabora gifted a Tier 1 sub to 4_vlasova_mar...,1
2341,2024-05-02 15:25:04 UTC,ardaabora,ardaabora gifted a Tier 1 sub to zhivagomd!,1
2342,2024-05-02 15:25:04 UTC,ardaabora,ardaabora gifted a Tier 1 sub to KLAUSsS18!,1
2343,2024-05-02 15:25:04 UTC,ardaabora,ardaabora gifted a Tier 1 sub to righter2iq!,1
2345,2024-05-02 15:25:04 UTC,ardaabora,ardaabora gifted a Tier 1 sub to duhkings!,1
2346,2024-05-02 15:25:04 UTC,ardaabora,ardaabora gifted a Tier 1 sub to drakuri02!,1
2373,2024-05-02 15:27:03 UTC,reflectsiam,reflectsiam gifted a Tier 1 sub to SveOdPriloga!,1
2374,2024-05-02 15:27:03 UTC,reflectsiam,reflectsiam gifted a Tier 1 sub to murad_123013!,1
2375,2024-05-02 15:27:03 UTC,reflectsiam,reflectsiam gifted a Tier 1 sub to chewycolour!,1
2376,2024-05-02 15:27:03 UTC,reflectsiam,reflectsiam gifted a Tier 1 sub to tufonova123!,1
2377,2024-05-02 15:27:03 UTC,reflectsiam,reflectsiam gifted a Tier 1 sub to dragazor69!,1
2382,2024-05-02 15:27:17 UTC,ardaabora,ardaabora gifted a Tier 1 sub to S4ffaron!,1
2383,2024-05-02 15:27:17 UTC,ardaabora,ardaabora gifted a Tier 1 sub to maniacreft46!,1
2384,2024-05-02 15:27:17 UTC,ardaabora,ardaabora gifted a Tier 1 sub to marcop_091!,1
2385,2024-05-02 15:27:17 UTC,ardaabora,ardaabora gifted a Tier 1 sub to oscardaztxx!,1
2386,2024-05-02 15:27:17 UTC,ardaabora,ardaabora gifted a Tier 1 sub to kauflandfps_!,1
2387,2024-05-02 15:27:17 UTC,ardaabora,ardaabora gifted a Tier 1 sub to 01863213936!,1
2388,2024-05-02 15:27:17 UTC,ardaabora,ardaabora gifted a Tier 1 sub to arnold_wyld!,1
2389,2024-05-02 15:27:17 UTC,ardaabora,ardaabora gifted a Tier 1 sub to gorbunova_occ...,1
2390,2024-05-02 15:27:17 UTC,ardaabora,ardaabora gifted a Tier 1 sub to rud_onji!,1

In [7]:
giftedData.describe()

            stream
count  1015.000000
mean     50.120197
std      22.355063
min       0.000000
25%      34.000000
50%      55.000000
75%      67.000000
max      87.000000

In [12]:
unique_gifter = giftedData['user'].nunique()
print("Number of unique users:", unique_gifter)

Number of unique users: 74